### ISSUE TITLE
RespondusLockDownBrowserLab.download.recipe unable to download

### ISSUE THREAD

**Issue by MLBZ521** [autopkg/nstrauss-recipes#22]
Respondus moved the Lab Edition download page behind a login.  So your `com.github.nstrauss.download.RespondusLockDownBrowserLab` recipe doesn't work anymore.

I have my own pkg recipe, which I've moved to using your standard edition download recipe (`com.github.nstrauss.download.RespondusLockDownBrowser`) instead and configuring the installation package to function as a Lab Edition package.

Just wanted to provide a PSA for anyone else looking at this.

**Comment by nstrauss** [comment]
@MLBZ521 Thanks for the heads up. I've been arguing with Respondus support for the past 10 days trying to convince them to revert the change their download URL for the lab version. I'm fairly sure they're sick of me at this point after I pointed out their additional security doesn't make the product more secure.

If you have a working version which writes the lab.txt file then please open a PR and I'll merge. I'd rather not have multiple versions floating around the autopkg community when possible. I was holding out hope Respondus would listen to reason sooner, but no such luck. Thanks.

**Comment by nstrauss** [comment]
Edited my recipes to copy the student package to include the lab hash and then run the install recipe. Updated the readme to include a link to your recipe as well. I really like your approach as well and think both are reasonable solutions. Excluding the install step in yours is admittedly a bit better. Going to stick with what I have for now since it's closer to the "supported" solution. Maybe one day Respondus will come to their senses.
