### ISSUE TITLE
Loom on M1 downloads intel pkg

### ISSUE THREAD

**Issue by rsaeks** [autopkg/nstrauss-recipes#23]
When running the Loom Download or pkg recipes on an M1 machine the x86 package is downloaded instead of arm64.

**Comment by nstrauss** [comment]
I'd already accounted for this with the `LoomArchPicker` processor, but didn't use an input variable which would be inherited by a recipe override. Updated the recipe to fix this. 06c5ababb371d0e1f44c56c243738480bcc2a505

1.  `autopkg repo-update nstrauss-recipes`
2. `autopkg make-override Loom.pkg.recipe`
3. Modify the recipe override to change the `LOOM_ARCH` input key to arm64 or x86 as necessary.
4. Run the recipe again.

I don't know if this is the best approach, but Loom should eventually ship a universal package. Since I am not currently using Loom, you or someone else may need to push on them to move that direction. No plans to update the processor to detect arch of the Mac running autopkg since it has no bearing on arch to which it's deployed.

It is possible to have two overrides - one for each arch. Simply rename one to something like Loom-arm64.pkg.recipe and set `LOOM_ARCH`. Then create another leaving the default x86 option in place.
