### ISSUE TITLE
Pearson/OnVUE.download.recipe - SEARCH_URL now returns a 404

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/nstrauss-recipes#57]
Hi,

Just looking to maybe use the OnVue recipes you've kindly supplied but these now fail with the below error:
`The following recipes failed:
    com.github.nstrauss.download.OnVUE
        Error in com.github.nstrauss.download.OnVUE: Processor: SimpleJSONParser: Error: 'osx_latest_version'`

Chucking the Search URL (https://op-prd-1.pvue2.com/proctorservst/api/v3/info/onvue) in a web browser or via Curl now returns a 404 error:
`{ "statusCode": 404, "message": "Resource not found" }`

I'm continuing to poke away at things but thought I'd raise it as so fair I'm not having much luck!

Thanks 
Daz

**Comment by nstrauss** [comment]
Thanks, Pearson. I poked around a little. Best I could find is https://system-test.onvue.com/system_test?customer=pearson_vue redirects to a download page with the current version, but isn't easily parseable since it's all JavaScript. Debugging the app itself and looking at `strings` didn't help much. It's an Electron app, doing Electron app stuff. 

Since I don't have a need for this recipe at the moment, I don't know much more time I can dedicate. There's probably a way to spelunk the version release feed, but I can't find (yet).

**Comment by Daz-wallace** [comment]
Thanks @nstrauss that was the clue that I needed.
Looks like the following changes are needed:
- Search URL - `https://op-prd-1.pvue2.com/candidate-service-2/api/v1/info/onvue`
- json_key - `onvue_osx_latest_version`
- Codesigning requirement - `identifier "com.electron.onvue" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = Y75Z7G683Y`

PR incoming!

**Comment by nstrauss** [comment]
Resolved with https://github.com/autopkg/nstrauss-recipes/pull/58
